### ISSUE TITLE
May I ask what inputs of this projects

### ISSUE THREAD

**Issue by pokjnb** [aothms/ear#5]
When I run your EAR.sln in "win" file, may I ask what the input of the main(int argc, char** argv)  is?  If I want to debug this projects in VS2017, what files or inputs should I need?  Do I need to user blender at the same time?   Thanks

**Comment by aothms** [comment]
The file format is described here http://explauralisation.org/fileformat/ but your best bet is to install Blender and the addon. You need an older version of Blender though as the API has changed in the decade after EAR was released :) https://github.com/aothms/ear/issues/2

**Comment by pokjnb** [comment]
so I found a file named 'a.ear', is this what you mean? 
I have already installed the old version blender 2.60 and also opened your example. However some errors are in the scripts and I am working on it. Back to this file, so how does it generate? or did you jsut edit it using binary directly following your format setting?  Where should I put it in?
Thanks for your time :)

**Comment by aothms** [comment]
Writing https://github.com/aothms/ear/blob/master/blender/render_EAR/__init__.py#L144
Parsing https://github.com/aothms/ear/blob/master/src/Datatype.cpp https://github.com/aothms/ear/blob/master/src/EAR.cpp#L92
Command line should be `ear render a.ear` if I recall correctly https://github.com/aothms/ear/blob/master/src/EAR.cpp#L398

**Comment by pokjnb** [comment]
e.. OK I am trying to understand this process. 
Do u mean that: 
1. in blender, press "render" and get the file "a.ear" (_init_.py)
2. then use command "ear render a.ear", this file will be parsed automatically in C++ projects. (Datatype）
if I want to debug in VS2017, what I need is one file "a.ear" and put this as input to "int main(int argc, char** argv)" 
am I right?

**Comment by aothms** [comment]
Correct I think

argv[1] = render
argv[2] = a.ear

**Comment by pokjnb** [comment]
thank you!  I have found some clues in main function. 
this input should be " ear.exe render a.ear"  after running this project to get ear.exe which is argv[0]

I am working on generating  ear.exe and a.ear files correctly. 
Thanks for your time, and happy new year. :)
