### ISSUE TITLE
Could this algorithms have real-time performace?

### ISSUE THREAD

**Issue by pokjnb** [aothms/ear#8]
I know you use linear interpolate IR and convolution the inputs, but the keyframes is alread setted before rendering.  Could this algorithms deal with the real-time process?

**Comment by aothms** [comment]
If you substitute the ray-tracing implementation with a fast GPU-based implementation (I think there are open source GPU accelerated ray-tracing APIs out there these days) It'll make a massive difference. The current unoptimized raytracing code is not suitable, but should be easily swapped out with something more performant.

**Comment by pokjnb** [comment]
Thanks for the replay, brain box.
Although I may get the IR really fast, still need to conv the inputs signal. To get the real-time outputs,  you may know any method faster than "interpolate response" out there these days?

**Comment by aothms** [comment]
No I don't really know, the interesting thing is of course that since sound travels slowly this also gives you time for the computation. You can perhaps separate the responses for early and late reflections.

**Comment by pokjnb** [comment]
Thanks for your reply. Well u r right. some models indeed separate the response in terms of IS method which needs to know the room shape before calculating. I thought RT method has more advantages in this point. :P
