### ISSUE TITLE
About diffraction in this model

### ISSUE THREAD

**Issue by pokjnb** [aothms/ear#9]
Hi :)
So I do not find any calculation about diffraction in EAR, is there any possible that I have not find the right part? or you just didn't consider diffraction?
For this example: http://explauralisation.org/example1/.   There is a low wall in the room, probably the output contains diffraction? otherwise what is the low wall used for?
And for this example: http://explauralisation.org/example2/.  Sound becomes louder when people is near the piano, if only reflection calculation, how could that happen?  just interpolating the ir based the numbers of rays in different positions?

However, only all my assumptions above, waiting for your reply.

**Comment by aothms** [comment]
No, there isn't diffraction. One way to implement that in ray-traced acoustics is to automatically generate "fins" connected to the convex edges of your mesh that somehow capture and bend incoming rays.

**Comment by pokjnb** [comment]
Thanks for your reply.  A good model for a start. :)
